from src.defs.script_defs import DBType, DBSyntax, InputOutput
from src.utils import funcs as utils


def generate_html_report(db_type: DBType, sql_buffer, input_output: InputOutput):
    """Generate HTML report code for database schema comparison"""

    sql_buffer.write("\n")

    if db_type == DBType.PostgreSQL:
        sql_buffer.write("IF (htmlReport = True) THEN\n")
        sql_buffer.write("\tDECLARE \n")
        sql_buffer.write("\t\tresult_string text;\n")
        sql_buffer.write("\t\thtml_content text;\n")
        sql_buffer.write("\t\tnew_content text;\n")
        sql_buffer.write(f"\t\tinput_file text := '{input_output.html_template_path}';\n")
        sql_buffer.write(f"\t\toutput_file text := '{input_output.html_output_path}';\n")
        sql_buffer.write("\tBEGIN\n")
        sql_buffer.write("\t\t-- Generate the array data (tables and data entries)\n")
        sql_buffer.write("\t\tSELECT COALESCE(\n")
        sql_buffer.write("\t\t\t\t   json_agg(\n")
        sql_buffer.write("\t\t\t\t\t   json_build_object(\n")
        sql_buffer.write("\t\t\t\t\t\t   'schema', combined.table_schema,\n")
        sql_buffer.write("\t\t\t\t\t\t   'name', combined.table_name,\n")
        sql_buffer.write("\t\t\t\t\t\t   'type', combined.entry_type,\n")
        sql_buffer.write("\t\t\t\t\t\t   'status', combined.status\n")
        sql_buffer.write("\t\t\t\t\t   )\n")
        sql_buffer.write("\t\t\t\t   )::text,\n")
        sql_buffer.write("\t\t\t\t   '[]'\n")
        sql_buffer.write("\t\t\t   )\n")
        sql_buffer.write("\t\tINTO result_string\n")
        sql_buffer.write("\t\tFROM (\n")
        sql_buffer.write("\t\t\t-- Table schema entries\n")
        sql_buffer.write("\t\t\tSELECT ST.table_schema, ST.table_name, 'Table' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE ST.tablestat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 0 THEN 'equal'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 1 THEN 'left-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 2 THEN 'right-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 3 THEN 'different'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status\n")
        sql_buffer.write("\t\t\tFROM ScriptTables ST\n")
        sql_buffer.write("\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t-- Data entries (only when dataStat indicates difference)\n")
        sql_buffer.write("\t\t\tSELECT SD.table_schema, SD.table_name, 'Data' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE SD.dataStat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 3 THEN 'different'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status\n")
        sql_buffer.write("\t\t\tFROM ScriptTables SD\n")
        sql_buffer.write("\t\t\tWHERE SD.dataStat IS NOT NULL\n")
        sql_buffer.write("\t\t) combined;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Read the HTML template file\n")
        sql_buffer.write("\t\tSELECT pg_read_file(input_file) INTO html_content;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Replace the placeholder with actual data\n")
        sql_buffer.write("\t\tnew_content := replace(html_content, '[[reportInfo]]', result_string);\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\tRAISE NOTICE 'Replacement done. Writing file...';\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Create a table and use COPY TO with proper encoding\n")
        sql_buffer.write("\t\tDROP TABLE IF EXISTS temp_html_file;\n")
        sql_buffer.write("\t\tCREATE TEMP TABLE temp_html_file (html_content text);\n")
        sql_buffer.write("\t\tINSERT INTO temp_html_file VALUES (new_content);\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Copy with CSV format to avoid text formatting issues\n")
        sql_buffer.write("\t\tEXECUTE format('COPY temp_html_file TO %L WITH (FORMAT CSV, QUOTE E''\\x01'', DELIMITER E''\\x02'')', output_file);\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\tDROP TABLE temp_html_file;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\tRAISE NOTICE 'HTML report successfully created: %', output_file;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\tEXCEPTION\n")
        sql_buffer.write("\t\tWHEN OTHERS THEN\n")
        sql_buffer.write("\t\t\tRAISE NOTICE 'Error creating HTML report: %', SQLERRM;\n")
        sql_buffer.write("\tEND;\n")
        sql_buffer.write("END IF; --htmlReport\n")

    
    sql_buffer.write("\n")