from src.defs.script_defs import DBType, DBSyntax, ScriptingOptions
from src.utils import funcs as utils

#!got_data needs to be implemented
def generate_add_alter_drop_cols(db_type: DBType, sql_buffer, j2_alter_cols_not_null, got_data: bool = False):
    """Generate SQL statements for adding, altering, and dropping columns."""
    
    # Adding Columns
    sql_buffer.write("\n")
    sql_buffer.write("--Adding Columns\n")
    
    if db_type == DBType.MSSQL:
        sql_buffer.write("DECLARE misCols CURSOR FAST_FORWARD \n")
        sql_buffer.write("FOR \n")
        sql_buffer.write("\tSELECT  C.table_schema , \n")
        sql_buffer.write("\t\tC.table_name, \n")
        sql_buffer.write("\t\tC.col_name, \n")
        sql_buffer.write("\t\tC.SQL_CREATE \n")
        sql_buffer.write("\tFROM    #ScriptCols C INNER JOIN #ScriptTables T on C.table_schema=T.table_schema AND C.table_name = T.table_name \n")
        sql_buffer.write("\tWHERE colStat = 1 AND T.tableStat=3 \n")
        sql_buffer.write("\t\tOPEN misCols \n")
        sql_buffer.write("FETCH NEXT FROM misCols INTO @table_schema, @table_name, @col_name, \n")
        sql_buffer.write("\t@SQL_CREATE \n")
        sql_buffer.write("WHILE @@FETCH_STATUS = 0  \n")
        sql_buffer.write("\tBEGIN \n")
        utils.add_print(db_type, 1, sql_buffer, "'Table ['+@table_schema+'].['+@table_name+']: adding column ['+@col_name+']'")
        sql_buffer.write("\t\tSET @sqlCode = @SQL_CREATE \n")
        utils.add_exec_sql(db_type, 1, sql_buffer)
        sql_buffer.write("\n")
        sql_buffer.write("\tFETCH NEXT FROM misCols INTO @table_schema, @table_name, @col_name, \n")
        sql_buffer.write("\t\t@SQL_CREATE \n")
        sql_buffer.write("END\n")
        sql_buffer.write("\n")
        sql_buffer.write("CLOSE misCols\n")
        sql_buffer.write("DEALLOCATE misCols\n")
    
    elif db_type == DBType.PostgreSQL:
        sql_buffer.write("declare temprow record;\n")
        sql_buffer.write("BEGIN\n")
        sql_buffer.write("\tFOR temprow IN \n")
        sql_buffer.write("\t\tSELECT  C.table_schema , \n")
        sql_buffer.write("\t\tC.table_name, \n")
        sql_buffer.write("\t\tC.col_name, \n")
        sql_buffer.write("\t\tC.SQL_CREATE \n")
        sql_buffer.write("\t\tFROM    ScriptCols C INNER JOIN ScriptTables T on LOWER(C.table_schema) = LOWER(T.table_schema) AND LOWER(C.table_name) = LOWER(T.table_name) \n")
        sql_buffer.write("\t\tWHERE colStat = 1 AND T.tableStat=3 \n")
        sql_buffer.write("\tLOOP\n")
        utils.add_print(db_type, 1, sql_buffer, "'Table ' || temprow.table_schema ||  '.' || temprow.table_name ||': adding column ' || temprow.col_name")
        utils.add_exec_sql(db_type, 1, sql_buffer, "temprow.SQL_CREATE")
        sql_buffer.write("\tEND LOOP;\n")
        sql_buffer.write("END; --of cursor \n")
    
    sql_buffer.write("\n")
    
    # Altering Columns
    sql_buffer.write("--Altering Columns\n")
    
    if db_type == DBType.MSSQL:
        sql_buffer.write("DECLARE alterCols CURSOR FAST_FORWARD \n")
        sql_buffer.write("FOR \n")
        sql_buffer.write("\tSELECT  table_schema , \n")
        sql_buffer.write("\t\ttable_name, \n")
        sql_buffer.write("\t\tcol_name, \n")
        sql_buffer.write("\t\tSQL_ALTER, \n")
        sql_buffer.write("\t\tdiff_descr \n")
        sql_buffer.write("\tFROM    #ScriptCols \n")
        sql_buffer.write("\tWHERE colStat = 3 \n")
        sql_buffer.write("\t\tOPEN alterCols \n")
        sql_buffer.write("FETCH NEXT FROM alterCols INTO @table_schema, @table_name, @col_name,@SQL_ALTER, @diff_descr \n")
        sql_buffer.write("WHILE @@FETCH_STATUS = 0  \n")
        sql_buffer.write("\tBEGIN \n")
        utils.add_print(db_type, 1, sql_buffer, "'Table ['+@table_schema+'].['+@table_name+']: column ['+@col_name+'] needs to be changed: '+@diff_descr")
        sql_buffer.write("\t\tSET @sqlCode = @SQL_ALTER \n")
        utils.add_exec_sql(db_type, 1, sql_buffer)
        sql_buffer.write("\n")
        sql_buffer.write("\tFETCH NEXT FROM alterCols INTO @table_schema, @table_name, @col_name,@SQL_ALTER, @diff_descr \n")
        sql_buffer.write("END\n")
        sql_buffer.write("\n")
        sql_buffer.write("CLOSE alterCols\n")
        sql_buffer.write("DEALLOCATE alterCols\n")
    
    elif db_type == DBType.PostgreSQL:
        sql_buffer.write("declare temprow record;\n")
        sql_buffer.write("BEGIN\n")
        sql_buffer.write("\tFOR temprow IN \n")
        sql_buffer.write("\t\tSELECT  C.table_schema , \n")
        sql_buffer.write("\t\tC.table_name, \n")
        sql_buffer.write("\t\tC.col_name, \n")
        sql_buffer.write("\t\tC.SQL_ALTER, \n")
        sql_buffer.write("\t\tC.diff_descr \n")
        sql_buffer.write("\t\tFROM  ScriptCols C\n")
        sql_buffer.write("\t\tWHERE colStat = 3\n")
        sql_buffer.write("\tLOOP\n")
        utils.add_print(db_type, 1, sql_buffer, "'Table ' || temprow.table_schema ||  '.' || temprow.table_name ||': column ' || temprow.col_name || ' needs to be changed: ' || temprow.diff_descr")
        utils.add_exec_sql(db_type, 1, sql_buffer, "temprow.SQL_ALTER")
        sql_buffer.write("\tEND LOOP;\n")
        sql_buffer.write("END; --of cursor \n")
    
    sql_buffer.write("\n")
    
    # Dropping Columns
    sql_buffer.write("--Dropping Columns\n")
    
    if db_type == DBType.MSSQL:
        sql_buffer.write("DECLARE extraCols CURSOR FAST_FORWARD \n")
        sql_buffer.write("FOR \n")
        sql_buffer.write("\tSELECT  table_schema , \n")
        sql_buffer.write("\t\ttable_name, \n")
        sql_buffer.write("\t\tcol_name, \n")
        sql_buffer.write("\t\tSQL_DROP \n")
        sql_buffer.write("\tFROM    #ScriptCols \n")
        sql_buffer.write("\tWHERE colStat = 2 \n")
        sql_buffer.write("\t\tOPEN extraCols \n")
        sql_buffer.write("FETCH NEXT FROM extraCols INTO @table_schema, @table_name, @col_name, \n")
        sql_buffer.write("\t@SQL_DROP \n")
        sql_buffer.write("WHILE @@FETCH_STATUS = 0  \n")
        sql_buffer.write("\tBEGIN \n")
        utils.add_print(db_type, 1, sql_buffer, "'Table ['+@table_schema+'].['+@table_name+']: dropping column ['+@col_name+']'")
        sql_buffer.write("\t\tSET @sqlCode = @SQL_DROP \n")
        utils.add_exec_sql(db_type, 1, sql_buffer)
        sql_buffer.write("\n")
        sql_buffer.write("\tFETCH NEXT FROM extraCols INTO @table_schema, @table_name, @col_name, \n")
        sql_buffer.write("\t\t@SQL_DROP \n")
        sql_buffer.write("END\n")
        sql_buffer.write("\n")
        sql_buffer.write("CLOSE extraCols\n")
        sql_buffer.write("DEALLOCATE extraCols\n")
    
    elif db_type == DBType.PostgreSQL:
        sql_buffer.write("declare temprow record;\n")
        sql_buffer.write("BEGIN\n")
        sql_buffer.write("\tFOR temprow IN \n")
        sql_buffer.write("\tSELECT  C.table_schema , \n")
        sql_buffer.write("\t\tC.table_name, \n")
        sql_buffer.write("\t\tC.col_name, \n")
        sql_buffer.write("\t\tC.SQL_DROP \n")
        sql_buffer.write("\tFROM    ScriptCols C \n")
        sql_buffer.write("\tWHERE colStat = 2 \n")
        sql_buffer.write("\tLOOP\n")
        utils.add_print(db_type, 1, sql_buffer, "'Table ' || temprow.table_schema ||  '.' || temprow.table_name ||': dropping column ' || temprow.col_name")
        utils.add_exec_sql(db_type, 1, sql_buffer, "temprow.SQL_DROP")
        sql_buffer.write("\tEND LOOP;\n")
        sql_buffer.write("END; --of cursor \n")
    
    sql_buffer.write("\n")
    
    # Setting NOT NULL after data insertion
    if got_data:  
        j2_alter_cols_not_null.write("\n")
        j2_alter_cols_not_null.write("--Now that I got the data: some columns may need to be set to NOT NULL\n")
        
        if db_type == DBType.MSSQL:
            j2_alter_cols_not_null.write("DECLARE @SQL_ALTER_PostData_NotNULL NVARCHAR(max)\n")
            j2_alter_cols_not_null.write("DECLARE alterCols CURSOR FAST_FORWARD \n")
            j2_alter_cols_not_null.write("FOR \n")
            j2_alter_cols_not_null.write("\tSELECT  table_schema , \n")
            j2_alter_cols_not_null.write("\t\ttable_name, \n")
            j2_alter_cols_not_null.write("\t\tcol_name, \n")
            j2_alter_cols_not_null.write("\t\tSQL_ALTER_PostData_NotNULL \n")
            j2_alter_cols_not_null.write("\tFROM    #ScriptCols \n")
            j2_alter_cols_not_null.write("\tWHERE colStat = 1 AND SQL_ALTER_PostData_NotNULL IS NOT NULL \n")
            j2_alter_cols_not_null.write("\t\tOPEN alterCols \n")
            j2_alter_cols_not_null.write("FETCH NEXT FROM alterCols INTO @table_schema, @table_name, @col_name,@SQL_ALTER_PostData_NotNULL \n")
            j2_alter_cols_not_null.write("WHILE @@FETCH_STATUS = 0  \n")
            j2_alter_cols_not_null.write("\tBEGIN \n")
            utils.add_print(db_type, 1, j2_alter_cols_not_null, "'Table ['+@table_schema+'].['+@table_name+']: column ['+@col_name+'] needs to be changed to NOT NULL, now that I got the data:'")
            j2_alter_cols_not_null.write("\t\tSET @sqlCode = @SQL_ALTER_PostData_NotNULL \n")
            utils.add_exec_sql(db_type, 1, j2_alter_cols_not_null)
            j2_alter_cols_not_null.write("\n")
            j2_alter_cols_not_null.write("\tFETCH NEXT FROM alterCols INTO @table_schema, @table_name, @col_name,@SQL_ALTER_PostData_NotNULL \n")
            j2_alter_cols_not_null.write("END\n")
            j2_alter_cols_not_null.write("\n")
            j2_alter_cols_not_null.write("CLOSE alterCols\n")
            j2_alter_cols_not_null.write("DEALLOCATE alterCols\n")
        
        elif db_type == DBType.PostgreSQL:
            j2_alter_cols_not_null.write("declare temprow record;\n")
            j2_alter_cols_not_null.write("BEGIN\n")
            j2_alter_cols_not_null.write("\tFOR temprow IN \n")
            j2_alter_cols_not_null.write("\tSELECT  C.table_schema , \n")
            j2_alter_cols_not_null.write("\t\tC.table_name, \n")
            j2_alter_cols_not_null.write("\t\tC.col_name, \n")
            j2_alter_cols_not_null.write("\t\tC.SQL_ALTER_PostData_NotNULL \n")
            j2_alter_cols_not_null.write("\tFROM    ScriptCols C \n")
            j2_alter_cols_not_null.write("\tWHERE colStat = 1  AND SQL_ALTER_PostData_NotNULL IS NOT NULL \n")
            j2_alter_cols_not_null.write("\tLOOP\n")
            utils.add_print(db_type, 1, j2_alter_cols_not_null, "'Table ' || temprow.table_schema ||  '.' || temprow.table_name ||': column ' || temprow.col_name || ' needs to be changed to NOT NULL, now that I got the data:'")
            utils.add_exec_sql(db_type, 1, j2_alter_cols_not_null, "temprow.SQL_ALTER_PostData_NotNULL")
            j2_alter_cols_not_null.write("\tEND LOOP;\n")
            j2_alter_cols_not_null.write("END; --of cursor \n")


def generate_drop_add_defaults(db_type: DBType, j2_defaults_drop, j2_defaults_add):
    """Generate SQL statements for dropping and adding default constraints."""
    
    # Dropping Defaults
    j2_defaults_drop.write("--Dropping Defaults that are different or their columns are different\n")
    
    if db_type == DBType.MSSQL:
        j2_defaults_drop.write("DECLARE @default_name NVARCHAR(128)\n")
        j2_defaults_drop.write("DECLARE dropDefault CURSOR FAST_FORWARD \n")
        j2_defaults_drop.write("FOR \n")
        j2_defaults_drop.write("\tSELECT  D.table_schema , \n")
        j2_defaults_drop.write("\t\tD.table_name, \n")
        j2_defaults_drop.write("\t\tdefault_name \n")
        j2_defaults_drop.write("\tFROM    #ScriptDefaults D\n")
        j2_defaults_drop.write("\tINNER JOIN #ScriptTables T ON D.table_schema = T.table_schema AND D.table_name = T.table_name \n")
        j2_defaults_drop.write("\tWHERE (defaultStat in (2,3) OR D.col_diff=1)  --extra, different \n")
        j2_defaults_drop.write("\t\tAND (T.tableStat NOT IN ( 1, 2 ) OR t.tableStat IS NULL)\n")
        j2_defaults_drop.write("\t\tOPEN dropDefault \n")
        j2_defaults_drop.write("FETCH NEXT FROM dropDefault INTO @table_schema, @table_name, @default_name \n")
        j2_defaults_drop.write("WHILE @@FETCH_STATUS = 0  \n")
        j2_defaults_drop.write("\tBEGIN \n")
        utils.add_print(db_type, 1, j2_defaults_drop, "'Table ['+@table_schema+'].['+@table_name+']: dropping default ['+@default_name+']'")
        j2_defaults_drop.write("\t\tSET @sqlCode = 'ALTER TABLE ['+@table_schema+'].['+@table_name+'] DROP CONSTRAINT ['+@default_name+']' \n")
        utils.add_exec_sql(db_type, 1, j2_defaults_drop)
        j2_defaults_drop.write("\n")
        j2_defaults_drop.write("\tFETCH NEXT FROM dropDefault INTO @table_schema, @table_name, @default_name \n")
        j2_defaults_drop.write("END\n")
        j2_defaults_drop.write("\n")
        j2_defaults_drop.write("CLOSE dropDefault\n")
        j2_defaults_drop.write("DEALLOCATE dropDefault\n")
        j2_defaults_drop.write("\n")

        # Adding Defaults for MSSQL
        j2_defaults_add.write("--Add Defaults: new, or ones dropped before because they were different or underlying columns where different\n")
        j2_defaults_add.write("DECLARE addDefault CURSOR FAST_FORWARD \n")
        j2_defaults_add.write("FOR \n")
        j2_defaults_add.write("\tSELECT  D.table_schema , \n")
        j2_defaults_add.write("\t\tD.table_name, \n")
        j2_defaults_add.write("\t\tD.default_name, \n")
        j2_defaults_add.write("\t\tD.SQL_CREATE \n")
        j2_defaults_add.write("\tFROM    #ScriptDefaults  D \n")
        j2_defaults_add.write("\tINNER JOIN #ScriptTables T ON D.table_schema = T.table_schema \n")
        j2_defaults_add.write("\tAND D.table_name = T.table_name \n")
        j2_defaults_add.write("\tWHERE (defaultStat in (1,3) OR D.col_diff=1)--extra or different \n")
        j2_defaults_add.write("\t\tAND (T.tableStat NOT IN ( 1, 2 ) OR t.tableStat IS NULL)\n")
        j2_defaults_add.write("\t\tOPEN addDefault \n")
        j2_defaults_add.write("FETCH NEXT FROM addDefault INTO @table_schema, @table_name, @default_name, @SQL_CREATE \n")
        j2_defaults_add.write("WHILE @@FETCH_STATUS = 0  \n")
        j2_defaults_add.write("\tBEGIN \n")
        utils.add_print(db_type, 1, j2_defaults_add, "'Table ['+@table_schema+'].['+@table_name+']: adding default ['+@default_name+']'")
        j2_defaults_add.write("\t\tSET @sqlCode = @SQL_CREATE \n")
        utils.add_exec_sql(db_type, 1, j2_defaults_add)
        j2_defaults_add.write("\n")
        j2_defaults_add.write("\tFETCH NEXT FROM addDefault INTO @table_schema, @table_name, @default_name, @SQL_CREATE \n")
        j2_defaults_add.write("END\n")
        j2_defaults_add.write("\n")
        j2_defaults_add.write("CLOSE addDefault\n")
        j2_defaults_add.write("DEALLOCATE addDefault\n")
        j2_defaults_add.write("\n")
    
    elif db_type == DBType.PostgreSQL:
        # Dropping Defaults for PostgreSQL
        j2_defaults_drop.write("\tdeclare temprow record;\n")
        j2_defaults_drop.write("\tBEGIN\n")
        j2_defaults_drop.write("\t\tFOR temprow IN\n")
        j2_defaults_drop.write("\t\tSELECT  D.table_schema , \n")
        j2_defaults_drop.write("\t\t\tD.table_name, \n")
        j2_defaults_drop.write("\t\t\tD.default_name, \n")
        j2_defaults_drop.write("\t\t\tD.col_name \n")
        j2_defaults_drop.write("\t\tFROM    ScriptDefaults D\n")
        j2_defaults_drop.write("\t\t\tINNER JOIN ScriptTables T ON D.table_schema = T.table_schema AND D.table_name = T.table_name \n")
        j2_defaults_drop.write("\t\tWHERE (defaultStat in (2,3) OR D.col_diff=true)  --extra, different \n")
        j2_defaults_drop.write("\t\t\tAND (T.tableStat NOT IN ( 1, 2 ) OR t.tableStat IS NULL)\n")
        j2_defaults_drop.write("\t\tLOOP \n")
        utils.add_print(db_type, 3, j2_defaults_drop, "'Table ' || temprow.table_schema || '.' || temprow.table_name || ': dropping default ' || temprow.default_name ")
        j2_defaults_drop.write("\t\t\tsqlCode = 'ALTER TABLE ' || temprow.table_schema || '.' || temprow.table_name || ' ALTER COLUMN ' || temprow.col_name || ' DROP DEFAULT;'; \n")
        utils.add_exec_sql(db_type, 3, j2_defaults_drop)
        j2_defaults_drop.write("\n")
        j2_defaults_drop.write("\t\tEND LOOP; \n")
        j2_defaults_drop.write("\tEND;\n")
        j2_defaults_drop.write("\n")

        # Adding Defaults for PostgreSQL
        j2_defaults_add.write("\tDECLARE temprow record;\n")
        j2_defaults_add.write("\tBEGIN\n")
        j2_defaults_add.write("\t\tFOR temprow IN\n")
        j2_defaults_add.write("\tSELECT  D.table_schema , \n")
        j2_defaults_add.write("\t\tD.table_name, \n")
        j2_defaults_add.write("\t\tD.default_name, \n")
        j2_defaults_add.write("\t\tD.SQL_CREATE \n")
        j2_defaults_add.write("\tFROM    ScriptDefaults  D \n")
        j2_defaults_add.write("\tINNER JOIN ScriptTables T ON LOWER(D.table_schema) = LOWER(T.table_schema) \n")
        j2_defaults_add.write("\tAND LOWER(D.table_name) = LOWER(T.table_name) \n")
        j2_defaults_add.write("\tWHERE (defaultStat in (1,3) OR D.col_diff=true)--extra or different \n")
        j2_defaults_add.write("\t\tAND (T.tableStat NOT IN ( 1, 2 ) OR t.tableStat IS NULL)\n")
        j2_defaults_add.write("LOOP \n")
        utils.add_print(db_type, 2, j2_defaults_add, "'Table [' || temprow.table_schema || '].[' || temprow.table_name || ']: adding default [' || temprow.default_name || ']'")
        j2_defaults_add.write("\t\tsqlCode = temprow.SQL_CREATE; \n")
        utils.add_exec_sql(db_type, 1, j2_defaults_add)
        j2_defaults_add.write("\n")
        j2_defaults_add.write("\tEND LOOP;\n")
        j2_defaults_add.write("END;\n")