from src.defs.script_defs import DBType, DBSyntax, InputOutput
from src.utils import funcs as utils


def generate_code_diffs(db_type: DBType, sql_buffer, input_output: InputOutput):
    """Generate HTML diff files for coded entities with differences (codeStat=3)"""

    sql_buffer.write("\n")

    if db_type == DBType.PostgreSQL:
        sql_buffer.write("IF (htmlReport = True) THEN\n")
        sql_buffer.write("\tDECLARE \n")
        sql_buffer.write("\t\tdiff_template text;\n")
        sql_buffer.write("\t\tdiff_content text;\n")
        sql_buffer.write("\t\tdiff_output_file text;\n")
        sql_buffer.write("\t\tscript_code_escaped text;\n")
        sql_buffer.write("\t\tdb_code_escaped text;\n")
        sql_buffer.write(f"\t\tdiff_template_path text := '{input_output.diff_template_path}';\n")
        sql_buffer.write(f"\t\tdiff_output_dir text := basePath;\n")
        sql_buffer.write("\t\tdiff_rec RECORD;\n")
        sql_buffer.write("\tBEGIN\n")
        sql_buffer.write("\t\t-- Read the diff template file\n")
        sql_buffer.write("\t\tSELECT pg_read_file(diff_template_path) INTO diff_template;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Loop through coded entities with differences\n")
        sql_buffer.write("\t\tFOR diff_rec IN \n")
        sql_buffer.write("\t\t\tSELECT \n")
        sql_buffer.write("\t\t\t\tsc.ent_schema,\n")
        sql_buffer.write("\t\t\t\tsc.ent_name,\n")
        sql_buffer.write("\t\t\t\tCOALESCE(sc.ent_type_pg, sc.ent_type) as ent_type,\n")
        sql_buffer.write("\t\t\t\tsc.param_type_list,\n")
        sql_buffer.write("\t\t\t\tsc.SQL_CREATE as script_code,\n")
        sql_buffer.write("\t\t\t\tdb_code.definition as db_code\n")
        sql_buffer.write("\t\t\tFROM ScriptCode sc\n")
        sql_buffer.write("\t\t\tINNER JOIN (\n")
        sql_buffer.write("\t\t\t\t-- Views\n")
        sql_buffer.write("\t\t\t\tSELECT v.table_schema as ent_schema, v.table_name as ent_name,\n")
        sql_buffer.write("\t\t\t\t\t'CREATE OR REPLACE VIEW ' || v.table_schema || '.' || v.table_name || E'\\nAS\\n' || v.view_definition AS definition,\n")
        sql_buffer.write("\t\t\t\t\t'' as param_type_list\n")
        sql_buffer.write("\t\t\t\tFROM information_schema.views v\n")
        sql_buffer.write("\t\t\t\tWHERE v.table_schema NOT IN ('information_schema', 'pg_catalog')\n")
        sql_buffer.write("\t\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t\t-- Functions/Procedures\n")
        sql_buffer.write("\t\t\t\tSELECT n.nspname as ent_schema, p.proname as ent_name,\n")
        sql_buffer.write("\t\t\t\t\tCASE WHEN l.lanname = 'internal' THEN p.prosrc\n")
        sql_buffer.write("\t\t\t\t\t\tELSE pg_get_functiondef(p.oid)\n")
        sql_buffer.write("\t\t\t\t\tEND as definition,\n")
        sql_buffer.write("\t\t\t\t\tpg_get_function_arguments(p.oid) as param_type_list\n")
        sql_buffer.write("\t\t\t\tFROM pg_proc p\n")
        sql_buffer.write("\t\t\t\tLEFT JOIN pg_namespace n ON p.pronamespace = n.oid\n")
        sql_buffer.write("\t\t\t\tLEFT JOIN pg_language l ON p.prolang = l.oid\n")
        sql_buffer.write("\t\t\t\tWHERE n.nspname NOT IN ('pg_catalog', 'information_schema')\n")
        sql_buffer.write("\t\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t\t-- Triggers\n")
        sql_buffer.write("\t\t\t\tSELECT t.trigger_schema as ent_schema, t.trigger_name as ent_name,\n")
        sql_buffer.write("\t\t\t\t\tt.action_statement as definition, '' as param_type_list\n")
        sql_buffer.write("\t\t\t\tFROM information_schema.triggers t\n")
        sql_buffer.write("\t\t\t\tGROUP BY t.trigger_schema, t.trigger_name, t.action_statement\n")
        sql_buffer.write("\t\t\t) db_code ON LOWER(sc.ent_schema) = LOWER(db_code.ent_schema)\n")
        sql_buffer.write("\t\t\t\tAND LOWER(sc.ent_name) = LOWER(db_code.ent_name)\n")
        sql_buffer.write("\t\t\t\tAND LOWER(COALESCE(sc.param_type_list, '')) = LOWER(COALESCE(db_code.param_type_list, ''))\n")
        sql_buffer.write("\t\t\tWHERE sc.codeStat = 3\n")
        sql_buffer.write("\t\tLOOP\n")
        sql_buffer.write("\t\t\t-- Generate filename: diff_schema_name_paramhash.html\n")
        sql_buffer.write("\t\t\tdiff_output_file := diff_output_dir || '/diff_' || \n")
        sql_buffer.write("\t\t\t\treplace(diff_rec.ent_schema, '.', '_') || '_' || \n")
        sql_buffer.write("\t\t\t\treplace(diff_rec.ent_name, '.', '_');\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\t-- Add param hash if there are parameters (for overloaded functions)\n")
        sql_buffer.write("\t\t\tIF diff_rec.param_type_list IS NOT NULL AND diff_rec.param_type_list <> '' THEN\n")
        sql_buffer.write("\t\t\t\tdiff_output_file := diff_output_file || '_' || \n")
        sql_buffer.write("\t\t\t\t\tmd5(diff_rec.param_type_list);\n")
        sql_buffer.write("\t\t\tEND IF;\n")
        sql_buffer.write("\t\t\tdiff_output_file := diff_output_file || '.html';\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\t-- Escape code for JavaScript (handle quotes, newlines, backslashes)\n")
        sql_buffer.write("\t\t\tscript_code_escaped := replace(replace(replace(replace(\n")
        sql_buffer.write("\t\t\t\tCOALESCE(diff_rec.script_code, ''),\n")
        sql_buffer.write("\t\t\t\t'\\', '\\\\'),  -- escape backslashes first\n")
        sql_buffer.write("\t\t\t\t'''', '\\'''),  -- escape single quotes\n")
        sql_buffer.write("\t\t\t\tE'\\n', '\\n'),  -- preserve newlines for JS\n")
        sql_buffer.write("\t\t\t\tE'\\r', '\\r');  -- preserve carriage returns for JS\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\tdb_code_escaped := replace(replace(replace(replace(\n")
        sql_buffer.write("\t\t\t\tCOALESCE(diff_rec.db_code, ''),\n")
        sql_buffer.write("\t\t\t\t'\\', '\\\\'),\n")
        sql_buffer.write("\t\t\t\t'''', '\\'''),\n")
        sql_buffer.write("\t\t\t\tE'\\n', '\\n'),\n")
        sql_buffer.write("\t\t\t\tE'\\r', '\\r');\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\t-- Build the diff content by replacing placeholders\n")
        sql_buffer.write("\t\t\tdiff_content := diff_template;\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[ENTITY_NAME]]', diff_rec.ent_name);\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[ENTITY_SCHEMA]]', diff_rec.ent_schema);\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[ENTITY_TYPE]]', diff_rec.ent_type);\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[SCRIPT_CODE]]', '''' || script_code_escaped || '''');\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[DB_CODE]]', '''' || db_code_escaped || '''');\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\t-- Write the diff file\n")
        sql_buffer.write("\t\t\tDROP TABLE IF EXISTS temp_diff_file;\n")
        sql_buffer.write("\t\t\tCREATE TEMP TABLE temp_diff_file (content text);\n")
        sql_buffer.write("\t\t\tINSERT INTO temp_diff_file VALUES (diff_content);\n")
        sql_buffer.write("\t\t\tEXECUTE format('COPY temp_diff_file TO %L WITH (FORMAT CSV, QUOTE E''\\x01'', DELIMITER E''\\x02'')', diff_output_file);\n")
        sql_buffer.write("\t\t\tDROP TABLE temp_diff_file;\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\tRAISE NOTICE 'Created diff file: %', diff_output_file;\n")
        sql_buffer.write("\t\tEND LOOP;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Loop through tables with differences\n")
        sql_buffer.write("\t\tFOR diff_rec IN \n")
        sql_buffer.write("\t\t\tSELECT \n")
        sql_buffer.write("\t\t\t\tst.table_schema,\n")
        sql_buffer.write("\t\t\t\tst.table_name,\n")
        sql_buffer.write("\t\t\t\t'Table' as ent_type,\n")
        sql_buffer.write("\t\t\t\t-- Script version: use the full SQL_CREATE from ScriptTables\n")
        sql_buffer.write("\t\t\t\tst.SQL_CREATE as script_code,\n")
        sql_buffer.write("\t\t\t\t-- DB version: build full CREATE TABLE from system catalogs\n")
        sql_buffer.write("\t\t\t\t(\n")
        sql_buffer.write("\t\t\t\t\t-- CREATE TABLE header\n")
        sql_buffer.write("\t\t\t\t\t'CREATE TABLE ' || st.table_schema || '.' || st.table_name || E'\\n(' || E'\\n' ||\n")
        sql_buffer.write("\t\t\t\t\t-- Columns\n")
        sql_buffer.write("\t\t\t\t\t(SELECT string_agg(\n")
        sql_buffer.write("\t\t\t\t\t\tc.column_name || ' ' || c.udt_name || \n")
        sql_buffer.write("\t\t\t\t\t\tCASE WHEN c.character_maximum_length IS NOT NULL THEN '(' || c.character_maximum_length || ')' ELSE '' END ||\n")
        sql_buffer.write("\t\t\t\t\t\tCASE WHEN c.is_nullable = 'YES' THEN ' NULL' ELSE ' NOT NULL' END ||\n")
        sql_buffer.write("\t\t\t\t\t\tCASE WHEN c.is_identity = 'YES' THEN ' GENERATED ' || c.identity_generation || ' AS IDENTITY' ELSE '' END ||\n")
        sql_buffer.write("\t\t\t\t\t\tCASE WHEN c.column_default IS NOT NULL AND c.is_identity = 'NO' THEN ' DEFAULT ' || c.column_default ELSE '' END,\n")
        sql_buffer.write("\t\t\t\t\t\tE',\\n' ORDER BY c.ordinal_position)\n")
        sql_buffer.write("\t\t\t\t\t FROM information_schema.columns c \n")
        sql_buffer.write("\t\t\t\t\t WHERE c.table_schema = st.table_schema AND c.table_name = st.table_name\n")
        sql_buffer.write("\t\t\t\t\t) || E'\\n);' ||\n")
        sql_buffer.write("\t\t\t\t\t-- Primary Key\n")
        sql_buffer.write("\t\t\t\t\tCOALESCE((\n")
        sql_buffer.write("\t\t\t\t\t\tSELECT E'\\nALTER TABLE ' || st.table_schema || '.' || st.table_name || \n")
        sql_buffer.write("\t\t\t\t\t\t\t' ADD CONSTRAINT ' || tc.constraint_name || ' PRIMARY KEY (' ||\n")
        sql_buffer.write("\t\t\t\t\t\t\tstring_agg(kcu.column_name, ', ' ORDER BY kcu.ordinal_position) || ');'\n")
        sql_buffer.write("\t\t\t\t\t\tFROM information_schema.table_constraints tc\n")
        sql_buffer.write("\t\t\t\t\t\tJOIN information_schema.key_column_usage kcu \n")
        sql_buffer.write("\t\t\t\t\t\t\tON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema\n")
        sql_buffer.write("\t\t\t\t\t\tWHERE tc.table_schema = st.table_schema AND tc.table_name = st.table_name\n")
        sql_buffer.write("\t\t\t\t\t\t\tAND tc.constraint_type = 'PRIMARY KEY'\n")
        sql_buffer.write("\t\t\t\t\t\tGROUP BY tc.constraint_name\n")
        sql_buffer.write("\t\t\t\t\t), '') ||\n")
        sql_buffer.write("\t\t\t\t\t-- Indexes (non-primary key, non-unique constraint)\n")
        sql_buffer.write("\t\t\t\t\tCOALESCE((\n")
        sql_buffer.write("\t\t\t\t\t\tSELECT string_agg(E'\\n' || indexdef || ';', '')\n")
        sql_buffer.write("\t\t\t\t\t\tFROM pg_indexes pi\n")
        sql_buffer.write("\t\t\t\t\t\tWHERE pi.schemaname = st.table_schema AND pi.tablename = st.table_name\n")
        sql_buffer.write("\t\t\t\t\t\t\tAND pi.indexname NOT IN (\n")
        sql_buffer.write("\t\t\t\t\t\t\t\tSELECT tc.constraint_name FROM information_schema.table_constraints tc\n")
        sql_buffer.write("\t\t\t\t\t\t\t\tWHERE tc.table_schema = st.table_schema AND tc.table_name = st.table_name\n")
        sql_buffer.write("\t\t\t\t\t\t\t\t\tAND tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE')\n")
        sql_buffer.write("\t\t\t\t\t\t\t)\n")
        sql_buffer.write("\t\t\t\t\t), '') ||\n")
        sql_buffer.write("\t\t\t\t\t-- Foreign Keys\n")
        sql_buffer.write("\t\t\t\t\tCOALESCE((\n")
        sql_buffer.write("\t\t\t\t\t\tSELECT string_agg(\n")
        sql_buffer.write("\t\t\t\t\t\t\tE'\\nALTER TABLE ' || tc.table_schema || '.' || tc.table_name ||\n")
        sql_buffer.write("\t\t\t\t\t\t\t' ADD CONSTRAINT ' || tc.constraint_name || ' FOREIGN KEY (' ||\n")
        sql_buffer.write("\t\t\t\t\t\t\t(SELECT string_agg(kcu.column_name, ', ' ORDER BY kcu.ordinal_position)\n")
        sql_buffer.write("\t\t\t\t\t\t\t FROM information_schema.key_column_usage kcu\n")
        sql_buffer.write("\t\t\t\t\t\t\t WHERE kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema) ||\n")
        sql_buffer.write("\t\t\t\t\t\t\t') REFERENCES ' ||\n")
        sql_buffer.write("\t\t\t\t\t\t\t(SELECT ccu.table_schema || '.' || ccu.table_name || '(' ||\n")
        sql_buffer.write("\t\t\t\t\t\t\t\tstring_agg(ccu.column_name, ', ') || ')'\n")
        sql_buffer.write("\t\t\t\t\t\t\t FROM information_schema.constraint_column_usage ccu\n")
        sql_buffer.write("\t\t\t\t\t\t\t WHERE ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema\n")
        sql_buffer.write("\t\t\t\t\t\t\t GROUP BY ccu.table_schema, ccu.table_name) || ';',\n")
        sql_buffer.write("\t\t\t\t\t\t\t'')\n")
        sql_buffer.write("\t\t\t\t\t\tFROM information_schema.table_constraints tc\n")
        sql_buffer.write("\t\t\t\t\t\tWHERE tc.table_schema = st.table_schema AND tc.table_name = st.table_name\n")
        sql_buffer.write("\t\t\t\t\t\t\tAND tc.constraint_type = 'FOREIGN KEY'\n")
        sql_buffer.write("\t\t\t\t\t), '')\n")
        sql_buffer.write("\t\t\t\t) as db_code\n")
        sql_buffer.write("\t\t\tFROM ScriptTables st\n")
        sql_buffer.write("\t\t\tWHERE st.tablestat = 3\n")
        sql_buffer.write("\t\tLOOP\n")
        sql_buffer.write("\t\t\t-- Generate filename: diff_table_schema_name.html\n")
        sql_buffer.write("\t\t\tdiff_output_file := diff_output_dir || '/diff_table_' || \n")
        sql_buffer.write("\t\t\t\treplace(diff_rec.table_schema, '.', '_') || '_' || \n")
        sql_buffer.write("\t\t\t\treplace(diff_rec.table_name, '.', '_') || '.html';\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\t-- Escape code for JavaScript\n")
        sql_buffer.write("\t\t\tscript_code_escaped := replace(replace(replace(replace(\n")
        sql_buffer.write("\t\t\t\tCOALESCE(diff_rec.script_code, ''),\n")
        sql_buffer.write("\t\t\t\t'\\', '\\\\'),\n")
        sql_buffer.write("\t\t\t\t'''', '\\'''),\n")
        sql_buffer.write("\t\t\t\tE'\\n', '\\n'),\n")
        sql_buffer.write("\t\t\t\tE'\\r', '\\r');\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\tdb_code_escaped := replace(replace(replace(replace(\n")
        sql_buffer.write("\t\t\t\tCOALESCE(diff_rec.db_code, ''),\n")
        sql_buffer.write("\t\t\t\t'\\', '\\\\'),\n")
        sql_buffer.write("\t\t\t\t'''', '\\'''),\n")
        sql_buffer.write("\t\t\t\tE'\\n', '\\n'),\n")
        sql_buffer.write("\t\t\t\tE'\\r', '\\r');\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\t-- Build the diff content\n")
        sql_buffer.write("\t\t\tdiff_content := diff_template;\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[ENTITY_NAME]]', diff_rec.table_name);\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[ENTITY_SCHEMA]]', diff_rec.table_schema);\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[ENTITY_TYPE]]', diff_rec.ent_type);\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[SCRIPT_CODE]]', '''' || script_code_escaped || '''');\n")
        sql_buffer.write("\t\t\tdiff_content := replace(diff_content, '[[DB_CODE]]', '''' || db_code_escaped || '''');\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\t-- Write the diff file\n")
        sql_buffer.write("\t\t\tDROP TABLE IF EXISTS temp_diff_file;\n")
        sql_buffer.write("\t\t\tCREATE TEMP TABLE temp_diff_file (content text);\n")
        sql_buffer.write("\t\t\tINSERT INTO temp_diff_file VALUES (diff_content);\n")
        sql_buffer.write("\t\t\tEXECUTE format('COPY temp_diff_file TO %L WITH (FORMAT CSV, QUOTE E''\\x01'', DELIMITER E''\\x02'')', diff_output_file);\n")
        sql_buffer.write("\t\t\tDROP TABLE temp_diff_file;\n")
        sql_buffer.write("\t\t\t\n")
        sql_buffer.write("\t\t\tRAISE NOTICE 'Created table diff file: %', diff_output_file;\n")
        sql_buffer.write("\t\tEND LOOP;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\tEXCEPTION\n")
        sql_buffer.write("\t\tWHEN OTHERS THEN\n")
        sql_buffer.write("\t\t\tRAISE NOTICE 'Error creating diff files: %', SQLERRM;\n")
        sql_buffer.write("\tEND;\n")
        sql_buffer.write("END IF; --htmlReport (code diffs)\n")

    sql_buffer.write("\n")
