import os
from src.defs.script_defs import DBType, DBSyntax, InputOutput
from src.utils import funcs as utils


def generate_html_report(db_type: DBType, sql_buffer, input_output: InputOutput):
    """Generate HTML report code for database schema comparison"""

    sql_buffer.write("\n")

    if db_type == DBType.PostgreSQL:
        sql_buffer.write("IF (htmlReport = True) THEN\n")
        sql_buffer.write("\tDECLARE \n")
        sql_buffer.write("\t\tresult_string text;\n")
        sql_buffer.write("\t\thtml_content text;\n")
        sql_buffer.write("\t\tnew_content text;\n")
        # Extract just the filename for use with basePath
        html_output_filename = os.path.basename(input_output.html_output_path)
        sql_buffer.write(f"\t\tinput_file text := '{input_output.html_template_path}';\n")
        sql_buffer.write(f"\t\toutput_file text := basePath || '/{html_output_filename}';\n")
        sql_buffer.write("\tBEGIN\n")
        sql_buffer.write("\t\t-- Generate the array data (tables and data entries)\n")
        sql_buffer.write("\t\tSELECT COALESCE(\n")
        sql_buffer.write("\t\t\t\t   json_agg(\n")
        sql_buffer.write("\t\t\t\t\t   json_build_object(\n")
        sql_buffer.write("\t\t\t\t\t\t   'schema', combined.table_schema,\n")
        sql_buffer.write("\t\t\t\t\t\t   'name', combined.table_name,\n")
        sql_buffer.write("\t\t\t\t\t\t   'type', combined.entry_type,\n")
        sql_buffer.write("\t\t\t\t\t\t   'status', combined.status,\n")
        sql_buffer.write("\t\t\t\t\t\t   'diffFile', combined.diff_file\n")
        sql_buffer.write("\t\t\t\t\t   )\n")
        sql_buffer.write("\t\t\t\t   )::text,\n")
        sql_buffer.write("\t\t\t\t   '[]'\n")
        sql_buffer.write("\t\t\t   )\n")
        sql_buffer.write("\t\tINTO result_string\n")
        sql_buffer.write("\t\tFROM (\n")
        sql_buffer.write("\t\t\t-- Table schema entries\n")
        sql_buffer.write("\t\t\tSELECT ST.table_schema, ST.table_name, 'Table' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE ST.tablestat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 0 THEN 'equal'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 1 THEN 'left-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 2 THEN 'right-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 3 THEN 'different'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status,\n")
        sql_buffer.write("\t\t\t\t-- Generate diff file name for tables with differences\n")
        sql_buffer.write("\t\t\t\tCASE WHEN ST.tablestat = 3 THEN\n")
        sql_buffer.write("\t\t\t\t\t'diff_table_' || replace(ST.table_schema, '.', '_') || '_' || \n")
        sql_buffer.write("\t\t\t\t\treplace(ST.table_name, '.', '_') || '.html'\n")
        sql_buffer.write("\t\t\t\tELSE NULL\n")
        sql_buffer.write("\t\t\t\tEND as diff_file\n")
        sql_buffer.write("\t\t\tFROM ScriptTables ST\n")
        sql_buffer.write("\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t-- Data entries (only when dataStat indicates difference)\n")
        sql_buffer.write("\t\t\tSELECT SD.table_schema, SD.table_name, 'Data' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE SD.dataStat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 3 THEN 'different'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status,\n")
        sql_buffer.write("\t\t\t\t-- Data diff files use compare_ prefix\n")
        sql_buffer.write("\t\t\t\tCASE WHEN SD.dataStat = 3 THEN\n")
        sql_buffer.write("\t\t\t\t\t'compare_' || SD.table_schema || '_' || SD.table_name || '.html'\n")
        sql_buffer.write("\t\t\t\tELSE NULL\n")
        sql_buffer.write("\t\t\t\tEND as diff_file\n")
        sql_buffer.write("\t\t\tFROM ScriptTables SD\n")
        sql_buffer.write("\t\t\tWHERE SD.dataStat IS NOT NULL\n")
        sql_buffer.write("\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t-- Coded entities (functions, procedures, views, triggers)\n")
        sql_buffer.write("\t\t\tSELECT SC.ent_schema as table_schema, \n")
        sql_buffer.write("\t\t\t\tCASE WHEN SC.param_type_list IS NOT NULL AND SC.param_type_list <> '' \n")
        sql_buffer.write("\t\t\t\t\tTHEN SC.ent_name || '(' || SC.param_type_list || ')' \n")
        sql_buffer.write("\t\t\t\t\tELSE SC.ent_name \n")
        sql_buffer.write("\t\t\t\tEND as table_name,\n")
        sql_buffer.write("\t\t\t\tCOALESCE(SC.ent_type_pg, SC.ent_type) as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE SC.codeStat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 0 THEN 'equal'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 1 THEN 'left-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 2 THEN 'right-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 3 THEN 'different'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status,\n")
        sql_buffer.write("\t\t\t\t-- Generate diff file name for coded entities with differences\n")
        sql_buffer.write("\t\t\t\tCASE WHEN SC.codeStat = 3 THEN\n")
        sql_buffer.write("\t\t\t\t\t'diff_' || replace(SC.ent_schema, '.', '_') || '_' || \n")
        sql_buffer.write("\t\t\t\t\treplace(SC.ent_name, '.', '_') || \n")
        sql_buffer.write("\t\t\t\t\tCASE WHEN SC.param_type_list IS NOT NULL AND SC.param_type_list <> '' \n")
        sql_buffer.write("\t\t\t\t\t\tTHEN '_' || md5(SC.param_type_list) \n")
        sql_buffer.write("\t\t\t\t\t\tELSE '' \n")
        sql_buffer.write("\t\t\t\t\tEND || '.html'\n")
        sql_buffer.write("\t\t\t\tELSE NULL\n")
        sql_buffer.write("\t\t\t\tEND as diff_file\n")
        sql_buffer.write("\t\t\tFROM ScriptCode SC\n")
        sql_buffer.write("\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t-- Security: Roles\n")
        sql_buffer.write("\t\t\tSELECT 'security' as table_schema, SR.rolname as table_name, 'Role' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE SR.roleStat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 0 THEN 'equal'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 1 THEN 'left-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 2 THEN 'right-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 3 THEN 'different'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status,\n")
        sql_buffer.write("\t\t\t\tNULL as diff_file\n")
        sql_buffer.write("\t\t\tFROM ScriptRoles SR\n")
        sql_buffer.write("\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t-- Security: Role Memberships\n")
        sql_buffer.write("\t\t\tSELECT 'security' as table_schema, \n")
        sql_buffer.write("\t\t\t\tSRM.member_name || ' IN ' || SRM.role_name as table_name, \n")
        sql_buffer.write("\t\t\t\t'Role Membership' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE SRM.membershipStat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 0 THEN 'equal'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 1 THEN 'left-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 2 THEN 'right-only'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status,\n")
        sql_buffer.write("\t\t\t\tNULL as diff_file\n")
        sql_buffer.write("\t\t\tFROM ScriptRoleMemberships SRM\n")
        sql_buffer.write("\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t-- Security: Table Permissions\n")
        sql_buffer.write("\t\t\tSELECT STP.table_schema, \n")
        sql_buffer.write("\t\t\t\tSTP.privilege_type || ' ON ' || STP.table_name || ' TO ' || STP.grantee as table_name,\n")
        sql_buffer.write("\t\t\t\t'Table Permission' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE STP.permStat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 0 THEN 'equal'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 1 THEN 'left-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 2 THEN 'right-only'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status,\n")
        sql_buffer.write("\t\t\t\tNULL as diff_file\n")
        sql_buffer.write("\t\t\tFROM ScriptTablePermissions STP\n")
        sql_buffer.write("\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t-- Security: Column Permissions\n")
        sql_buffer.write("\t\t\tSELECT SCP.table_schema, \n")
        sql_buffer.write("\t\t\t\tSCP.privilege_type || ' ON ' || SCP.table_name || '.' || SCP.column_name || ' TO ' || SCP.grantee as table_name,\n")
        sql_buffer.write("\t\t\t\t'Column Permission' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE SCP.permStat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 0 THEN 'equal'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 1 THEN 'left-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 2 THEN 'right-only'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status,\n")
        sql_buffer.write("\t\t\t\tNULL as diff_file\n")
        sql_buffer.write("\t\t\tFROM ScriptColumnPermissions SCP\n")
        sql_buffer.write("\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t-- Security: Function Permissions\n")
        sql_buffer.write("\t\t\tSELECT SFP.routine_schema as table_schema, \n")
        sql_buffer.write("\t\t\t\tSFP.privilege_type || ' ON ' || SFP.routine_name || ' TO ' || SFP.grantee as table_name,\n")
        sql_buffer.write("\t\t\t\t'Function Permission' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE SFP.permStat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 0 THEN 'equal'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 1 THEN 'left-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 2 THEN 'right-only'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status,\n")
        sql_buffer.write("\t\t\t\tNULL as diff_file\n")
        sql_buffer.write("\t\t\tFROM ScriptFunctionPermissions SFP\n")
        sql_buffer.write("\t\t\tUNION ALL\n")
        sql_buffer.write("\t\t\t-- Security: RLS Policies\n")
        sql_buffer.write("\t\t\tSELECT SRLSP.table_schema as table_schema, \n")
        sql_buffer.write("\t\t\t\tSRLSP.policy_name || ' ON ' || SRLSP.table_name as table_name,\n")
        sql_buffer.write("\t\t\t\t'RLS Policy' as entry_type,\n")
        sql_buffer.write("\t\t\t\tCASE SRLSP.policyStat\n")
        sql_buffer.write("\t\t\t\t\tWHEN 0 THEN 'equal'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 1 THEN 'left-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 2 THEN 'right-only'\n")
        sql_buffer.write("\t\t\t\t\tWHEN 3 THEN 'different'\n")
        sql_buffer.write("\t\t\t\t\tELSE 'equal'\n")
        sql_buffer.write("\t\t\t\tEND as status,\n")
        sql_buffer.write("\t\t\t\tNULL as diff_file\n")
        sql_buffer.write("\t\t\tFROM ScriptRLSPolicies SRLSP\n")
        sql_buffer.write("\t\t) combined;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Read the HTML template file\n")
        sql_buffer.write("\t\tSELECT pg_read_file(input_file) INTO html_content;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Replace the placeholder with actual data\n")
        sql_buffer.write("\t\tnew_content := replace(html_content, '[[reportInfo]]', result_string);\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\tRAISE NOTICE 'Replacement done. Writing file...';\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Create a table and use COPY TO with proper encoding\n")
        sql_buffer.write("\t\tDROP TABLE IF EXISTS temp_html_file;\n")
        sql_buffer.write("\t\tCREATE TEMP TABLE temp_html_file (html_content text);\n")
        sql_buffer.write("\t\tINSERT INTO temp_html_file VALUES (new_content);\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\t-- Copy with CSV format to avoid text formatting issues\n")
        sql_buffer.write("\t\tEXECUTE format('COPY temp_html_file TO %L WITH (FORMAT CSV, QUOTE E''\\x01'', DELIMITER E''\\x02'')', output_file);\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\tDROP TABLE temp_html_file;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\t\tRAISE NOTICE 'HTML report successfully created: %', output_file;\n")
        sql_buffer.write("\t\t\n")
        sql_buffer.write("\tEXCEPTION\n")
        sql_buffer.write("\t\tWHEN OTHERS THEN\n")
        sql_buffer.write("\t\t\tRAISE NOTICE 'Error creating HTML report: %', SQLERRM;\n")
        sql_buffer.write("\tEND;\n")
        sql_buffer.write("END IF; --htmlReport\n")

    
    sql_buffer.write("\n")