"""
A restored database has to be writable afterwards.

The script inserts rows with their keys spelled out - INSERT ... OVERRIDING SYSTEM VALUE VALUES ('1', ...) -
and supplying an identity value explicitly does not advance the sequence behind it. So a restored table
held ids up to 10 while its sequence still sat at 1, and the first insert that let PostgreSQL choose the
key failed:

    ERROR:  duplicate key value violates unique constraint "staff_pkey"
    Key (id)=(3) already exists.

Nothing the script does would ever hit this - only whatever uses the database next. Which is why no test
caught it: every test, and every run, supplied the key. The one below does not, and that is the whole
point of it.
"""
import json
import os
import subprocess
import sys
import uuid
from pathlib import Path

import psycopg2
import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from tests.conftest import load_test_config

PROJECT = Path(__file__).parent.parent.parent.parent

SOURCE_SQL = """
CREATE SCHEMA app;
-- an identity column, a serial column, and a table with neither
CREATE TABLE app.identity_rows (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL);
CREATE TABLE app.serial_rows   (id serial PRIMARY KEY, name text NOT NULL);
CREATE TABLE app.plain_rows    (code text PRIMARY KEY, name text NOT NULL);
INSERT INTO app.identity_rows (id, name) OVERRIDING SYSTEM VALUE
    SELECT g, 'row ' || g FROM generate_series(1, 7) g;
INSERT INTO app.serial_rows (id, name) SELECT g, 'row ' || g FROM generate_series(1, 4) g;
INSERT INTO app.plain_rows (code, name) VALUES ('a', 'first'), ('b', 'second');
"""


def admin_connection():
    cfg = load_test_config()
    conn = psycopg2.connect(host=cfg.host, database='postgres', user=cfg.user,
                            password=cfg.password, port=cfg.port)
    conn.autocommit = True
    return conn


def db_connection(db_name):
    cfg = load_test_config()
    conn = psycopg2.connect(host=cfg.host, database=db_name, user=cfg.user,
                            password=cfg.password, port=cfg.port)
    conn.autocommit = True
    return conn


def run_sql(conn, sql):
    with conn.cursor() as cur:
        cur.execute(sql)


def generate(db_name, work_dir):
    cfg = load_test_config()
    out_sql = os.path.join(work_dir, 'seq.sql')
    config = {
        'database': {'host': cfg.host, 'db_name': db_name, 'user': cfg.user,
                     'password': cfg.password, 'port': cfg.port},
        'scripting_options': {'remove_all_extra_ents': True, 'script_security': False, 'all_schemas': True},
        'table_script_ops': {'column_identity': True, 'indexes': True, 'foreign_keys': True,
                             'defaults': True, 'check_constraints': True},
        'db_ents_to_load': {'tables': [], 'schemas': []},
        'tables_data': {'tables': [], 'schemas': [], 'script_data': True},
        'input_output': {'html_template_path': '', 'html_output_path': os.path.join(work_dir, 'r.html'),
                         'diff_template_path': '', 'diff_output_dir': work_dir, 'output_sql': out_sql},
        # print_exec has to be on. It is what fills scriptoutput, which is the only way a test can see
        # what the script decided to do - with it off, 'did the second run report anything' reads an
        # empty table and passes whatever the script did. That is exactly how the setval that reported
        # itself for ever got past the test written to catch it
        'sql_script_params': {'print': False, 'print_exec': True, 'exec_code': True,
                              'html_report': False, 'export_csv': False},
    }
    path = os.path.join(work_dir, 'config.json')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(config, f)
    result = subprocess.run([sys.executable, '-m', 'src.main', path],
                            capture_output=True, text=True, cwd=str(PROJECT))
    assert result.returncode == 0, f'generating failed: {result.stderr[-2000:]}'
    with open(out_sql, encoding='utf-8') as f:
        return f.read()


@pytest.mark.data
@pytest.mark.slow
def test_a_restored_table_can_be_inserted_into_without_naming_the_key(tmp_path):
    source = 'cfs_seq_s_' + uuid.uuid4().hex[:8]
    target = 'cfs_seq_t_' + uuid.uuid4().hex[:8]
    admin = admin_connection()
    run_sql(admin, f'CREATE DATABASE {source}')
    run_sql(admin, f'CREATE DATABASE {target}')
    try:
        conn = db_connection(source)
        try:
            run_sql(conn, SOURCE_SQL)
        finally:
            conn.close()

        script = generate(source, str(tmp_path))

        conn = db_connection(target)
        try:
            with conn.cursor() as cur:
                cur.execute(script)

            # The restore is done. Now do what the script never does: let PostgreSQL pick the key
            with conn.cursor() as cur:
                cur.execute("INSERT INTO app.identity_rows (name) VALUES ('after restore') RETURNING id")
                identity_id = cur.fetchone()[0]
                cur.execute("INSERT INTO app.serial_rows (name) VALUES ('after restore') RETURNING id")
                serial_id = cur.fetchone()[0]
                cur.execute('SELECT count(*) FROM app.plain_rows')
                plain_rows = cur.fetchone()[0]
        finally:
            conn.close()
    finally:
        run_sql(admin, f'DROP DATABASE IF EXISTS {source} WITH (FORCE)')
        run_sql(admin, f'DROP DATABASE IF EXISTS {target} WITH (FORCE)')
        admin.close()

    assert identity_id == 8, (
        f'the identity sequence was left behind the data: the next id came out {identity_id}, not 8')
    assert serial_id == 5, (
        f'the serial sequence was left behind the data: the next id came out {serial_id}, not 5')
    assert plain_rows == 2, 'a table with no sequence should be unaffected'


@pytest.mark.data
@pytest.mark.slow
def test_the_resync_is_quiet_about_tables_that_have_no_sequence(tmp_path):
    """And a second run still settles - setval must not read as a change."""
    source = 'cfs_seq_s_' + uuid.uuid4().hex[:8]
    target = 'cfs_seq_t_' + uuid.uuid4().hex[:8]
    admin = admin_connection()
    run_sql(admin, f'CREATE DATABASE {source}')
    run_sql(admin, f'CREATE DATABASE {target}')
    try:
        conn = db_connection(source)
        try:
            run_sql(conn, SOURCE_SQL)
        finally:
            conn.close()
        script = generate(source, str(tmp_path))

        # the resync is emitted per sequence-backed column, and plain_rows has none
        assert script.count('setval') == 2, (
            f"expected one setval per sequence-backed column, got {script.count('setval')}")
        assert 'plain_rows' not in script.split('--Putting identity')[1].split('END; --sequences')[0], (
            'a table with no sequence was given a setval'
        )

        conn = db_connection(target)
        try:
            with conn.cursor() as cur:
                cur.execute(script)
            with conn.cursor() as cur:
                cur.execute(script)
                settled = [r[0] for r in cur.fetchall() if r and r[0]]
        finally:
            conn.close()
    finally:
        run_sql(admin, f'DROP DATABASE IF EXISTS {source} WITH (FORCE)')
        run_sql(admin, f'DROP DATABASE IF EXISTS {target} WITH (FORCE)')
        admin.close()

    assert not settled, f'the second run still wanted to change things: {settled[:5]}'


@pytest.mark.data
@pytest.mark.slow
def test_the_script_reports_nothing_against_the_database_it_came_from(tmp_path):
    """
    The shortest statement of what this tool promises: run the script on its own source and there is
    nothing to do.

    The first version of the resync emitted setval unconditionally, so a script run against its own
    source reported two statements - and reported the same two every run afterwards, since executing
    them changed nothing. 'Run it until it says nothing' stopped terminating. The test above should have
    caught that and did not, because printing was off.

    The source's own sequences are put in step first, and that is the point rather than setup noise.
    SOURCE_SQL spells its keys out, so the source is itself in the state the resync exists to repair -
    and reporting a setval against such a database is correct, not a bug. The claim being made here is
    narrower and is the one the user hit: a database that already agrees with the script is left alone.

    Nothing is executed here: exec_code is irrelevant to the question, and a run that reports nothing
    has nothing to execute anyway.
    """
    source = 'cfs_seq_o_' + uuid.uuid4().hex[:8]
    admin = admin_connection()
    run_sql(admin, f'CREATE DATABASE {source}')
    try:
        conn = db_connection(source)
        try:
            run_sql(conn, SOURCE_SQL)
            for table in ('identity_rows', 'serial_rows'):
                run_sql(conn, f"SELECT setval(pg_get_serial_sequence('app.{table}', 'id'),"
                              f" (SELECT MAX(id) FROM app.{table}))")
        finally:
            conn.close()
        script = generate(source, str(tmp_path))

        conn = db_connection(source)
        try:
            with conn.cursor() as cur:
                cur.execute(script)
                reported = [r[0] for r in cur.fetchall() if r and r[0]]
        finally:
            conn.close()
    finally:
        run_sql(admin, f'DROP DATABASE IF EXISTS {source} WITH (FORCE)')
        admin.close()

    assert not reported, (
        'the script found work to do on the database it was generated from: ' + '; '.join(reported[:5]))
