"""
A table's diff page must show what really differs, and nothing else.

The page puts the script's CREATE TABLE beside the target's and diffs the text. The two sides were built
by different code and did not agree on what belongs in that text:

  - unique constraints were on the script's side but not the target's: the index list on the target side
    deliberately skips anything backing a PRIMARY KEY or UNIQUE constraint, and nothing added the unique
    ones back. Every table holding one showed 'ADD CONSTRAINT x UNIQUE (...)' as a difference.
  - foreign keys were the other way round: rendered for the target, absent from the script's side, which
    leaves them out on purpose because the script adds foreign keys after the data.

Either way the spurious line also pushed the diff out of step, so a neighbouring line - the primary key -
read as changed too. Three tables drifted by one column each showed six or seven differences.

Both sides now cover the same ground: columns, primary key, unique constraints, indexes. Foreign key
differences are still on the page, in the statement cards built from ScriptFKs and scriptoutput.
"""
import json
import os
import re
import subprocess
import sys
import uuid
from pathlib import Path

import psycopg2
import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from tests.conftest import load_test_config

PROJECT = Path(__file__).parent.parent.parent.parent

# A primary key, a single-column unique, a multi-column unique, an index and a foreign key - the shapes
# that were being rendered on one side only
SCHEMA_SQL = """
CREATE SCHEMA app;
CREATE TABLE app.students (
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     varchar(120) NOT NULL UNIQUE,
    full_name varchar(50)  NOT NULL,
    is_active boolean      NOT NULL DEFAULT true
);
CREATE TABLE app.grades (
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id int NOT NULL REFERENCES app.students(id),
    course     varchar(80) NOT NULL,
    mark       numeric(5,2) NOT NULL,
    CONSTRAINT uq_grades_student_course UNIQUE (student_id, course)
);
CREATE INDEX ix_grades_student_id ON app.grades (student_id);
"""

# One real change per table, and nothing else
DRIFT_SQL = """
ALTER TABLE app.students DROP COLUMN is_active;
ALTER TABLE app.grades ALTER COLUMN course TYPE varchar(40);
"""


def admin_connection():
    cfg = load_test_config()
    conn = psycopg2.connect(host=cfg.host, database='postgres', user=cfg.user,
                            password=cfg.password, port=cfg.port)
    conn.autocommit = True
    return conn


def db_connection(db_name):
    cfg = load_test_config()
    conn = psycopg2.connect(host=cfg.host, database=db_name, user=cfg.user,
                            password=cfg.password, port=cfg.port)
    conn.autocommit = True
    return conn


def run_sql(conn, sql):
    with conn.cursor() as cur:
        cur.execute(sql)


def generate_report(source_db, target_db, work_dir):
    cfg = load_test_config()
    work = Path(work_dir)
    source = {
        'database': {'host': cfg.host, 'db_name': source_db, 'user': cfg.user,
                     'password': cfg.password, 'port': cfg.port},
        'scripting_options': {'remove_all_extra_ents': True, 'script_security': False, 'all_schemas': True},
        'table_script_ops': {'column_identity': True, 'indexes': True, 'foreign_keys': True,
                             'defaults': True, 'check_constraints': True},
        'db_ents_to_load': {'tables': [], 'schemas': []},
        'tables_data': {'tables': [], 'schemas': [], 'script_data': False},
        'input_output': {'html_template_path': '', 'html_output_path': str(work / 'report.html'),
                         'diff_template_path': '', 'diff_output_dir': str(work),
                         'output_sql': str(work / 'out.sql')},
        'sql_script_params': {'print': False, 'print_exec': True, 'exec_code': False,
                              'html_report': True, 'export_csv': False},
    }
    (work / 'source.json').write_text(json.dumps(source), encoding='utf-8')
    (work / 'target.json').write_text(json.dumps(
        {'database': {'host': cfg.host, 'db_name': target_db, 'user': cfg.user,
                      'password': cfg.password, 'port': cfg.port}}), encoding='utf-8')

    result = subprocess.run([sys.executable, '-m', 'src.main', str(work / 'source.json'),
                             '--report-on', str(work / 'target.json')],
                            capture_output=True, text=True, cwd=str(PROJECT))
    assert result.returncode == 0, f'{result.stdout}\n{result.stderr}'
    return result


def two_sides(page_path):
    """The script and database CREATE TABLE text the page diffs, as lists of lines."""
    page = page_path.read_text(encoding='utf-8')
    sides = {}
    for name in ('scriptCode', 'dbCode'):
        found = re.search(rf"(?:const|let|var)\s+{name}\s*=\s*'(.*?)';\s*\n", page, re.S)
        assert found, f'{page_path.name} has no {name}'
        sides[name] = found.group(1).encode().decode('unicode_escape').splitlines()
    return sides['scriptCode'], sides['dbCode']


@pytest.mark.complex
@pytest.mark.slow
def test_a_table_diff_shows_only_what_really_differs(tmp_path):
    source_db = 'cfs_tdp_s_' + uuid.uuid4().hex[:8]
    target_db = 'cfs_tdp_t_' + uuid.uuid4().hex[:8]
    admin = admin_connection()
    run_sql(admin, f'CREATE DATABASE {source_db}')
    run_sql(admin, f'CREATE DATABASE {target_db}')
    try:
        for db in (source_db, target_db):
            conn = db_connection(db)
            try:
                run_sql(conn, SCHEMA_SQL)
            finally:
                conn.close()
        conn = db_connection(target_db)
        try:
            run_sql(conn, DRIFT_SQL)
        finally:
            conn.close()

        generate_report(source_db, target_db, tmp_path)
    finally:
        run_sql(admin, f'DROP DATABASE IF EXISTS {source_db} WITH (FORCE)')
        run_sql(admin, f'DROP DATABASE IF EXISTS {target_db} WITH (FORCE)')
        admin.close()

    pages = {p.name: p for p in tmp_path.glob('diff_table_*.html')}
    assert 'diff_table_app_students.html' in pages, f'no page for the drifted table: {sorted(pages)}'
    assert 'diff_table_app_grades.html' in pages, f'no page for the drifted table: {sorted(pages)}'

    for name, page in sorted(pages.items()):
        script_side, db_side = two_sides(page)
        only_script = [l for l in script_side if l not in db_side]
        only_db = [l for l in db_side if l not in script_side]

        # A unique constraint exists on both sides, so it must appear on both or neither
        for line in [l for l in script_side + db_side if 'UNIQUE' in l]:
            assert line in script_side and line in db_side, (
                f'{name}: a unique constraint is rendered on one side only, which reads as a difference '
                f'that is not there:\n  {line}')

        # Same for foreign keys: present on both sides or on neither
        for line in [l for l in script_side + db_side if 'FOREIGN KEY' in l]:
            assert line in script_side and line in db_side, (
                f'{name}: a foreign key is rendered on one side only:\n  {line}')

        # And the primary key is identical on both sides in every case here
        for line in [l for l in script_side + db_side if 'PRIMARY KEY' in l]:
            assert line in script_side and line in db_side, (
                f'{name}: the primary key reads as changed although nothing about it changed:\n  {line}')

        # The real drift, and only that: one column line per table
        differences = only_script + only_db
        column_lines = [l for l in differences if 'CONSTRAINT' not in l and 'CREATE' not in l]
        assert differences, f'{name}: nothing differs, so the drift did not take'
        assert len(column_lines) == len(differences), (
            f'{name}: something other than a column line differs:\n  ' + '\n  '.join(differences))


@pytest.mark.complex
@pytest.mark.slow
def test_identical_tables_have_no_diff_page_content_at_all(tmp_path):
    """Two databases built the same way must produce no table differences whatsoever."""
    source_db = 'cfs_tdp_s_' + uuid.uuid4().hex[:8]
    target_db = 'cfs_tdp_t_' + uuid.uuid4().hex[:8]
    admin = admin_connection()
    run_sql(admin, f'CREATE DATABASE {source_db}')
    run_sql(admin, f'CREATE DATABASE {target_db}')
    try:
        for db in (source_db, target_db):
            conn = db_connection(db)
            try:
                run_sql(conn, SCHEMA_SQL)
            finally:
                conn.close()
        result = generate_report(source_db, target_db, tmp_path)
    finally:
        run_sql(admin, f'DROP DATABASE IF EXISTS {source_db} WITH (FORCE)')
        run_sql(admin, f'DROP DATABASE IF EXISTS {target_db} WITH (FORCE)')
        admin.close()

    assert '0 statement(s) would be needed' in result.stdout, (
        'identical databases reported work to do:\n' + result.stdout)

    for page in tmp_path.glob('diff_table_*.html'):
        script_side, db_side = two_sides(page)
        assert script_side == db_side, (
            f'{page.name}: identical tables render differently\n'
            f'  only on the script side: {[l for l in script_side if l not in db_side]}\n'
            f'  only on the database side: {[l for l in db_side if l not in script_side]}')
