-- ============================================================
-- Students / Grades / Grades_Correspondance  (+ unrelated Staff)
-- PostgreSQL 10+  (tested shape for PG 18)
-- ============================================================

DROP TABLE IF EXISTS grades_correspondance CASCADE;
DROP TABLE IF EXISTS grades               CASCADE;
DROP TABLE IF EXISTS students             CASCADE;
DROP TABLE IF EXISTS staff                CASCADE;

-- ------------------------------------------------------------
-- 1. students  (parent)
-- ------------------------------------------------------------
CREATE TABLE students (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    varchar(50)  NOT NULL,
    last_name     varchar(50)  NOT NULL,
    email         varchar(120) NOT NULL UNIQUE,
    date_of_birth date         NOT NULL,
    enrolled_on   date         NOT NULL DEFAULT CURRENT_DATE,
    is_active     boolean      NOT NULL DEFAULT true
);

-- ------------------------------------------------------------
-- 2. grades  (child of students)
-- ------------------------------------------------------------
CREATE TABLE grades (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  integer      NOT NULL,
    course      varchar(80)  NOT NULL,
    grade       numeric(5,2) NOT NULL,
    graded_on   date         NOT NULL,
    CONSTRAINT fk_grades_student
        FOREIGN KEY (student_id) REFERENCES students (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT ck_grades_range   CHECK (grade >= 0 AND grade <= 100),
    CONSTRAINT uq_grades_student_course UNIQUE (student_id, course)
);

CREATE INDEX ix_grades_student_id ON grades (student_id);

-- ------------------------------------------------------------
-- 3. grades_correspondance  (child of grades — messages about a grade)
-- ------------------------------------------------------------
CREATE TABLE grades_correspondance (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_id     integer      NOT NULL,
    author       varchar(80)  NOT NULL,
    message_type varchar(20)  NOT NULL DEFAULT 'feedback',
    message      text         NOT NULL,
    sent_at      timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_correspondance_grade
        FOREIGN KEY (grade_id) REFERENCES grades (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT ck_correspondance_type
        CHECK (message_type IN ('feedback','query','appeal','notice'))
);

CREATE INDEX ix_correspondance_grade_id ON grades_correspondance (grade_id);

-- ------------------------------------------------------------
-- 4. staff  (standalone — no relationship to the others)
-- ------------------------------------------------------------
CREATE TABLE staff (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   varchar(100)  NOT NULL,
    role        varchar(60)   NOT NULL,
    department  varchar(60)   NOT NULL,
    email       varchar(120)  NOT NULL UNIQUE,
    hired_on    date          NOT NULL,
    salary      numeric(10,2) NOT NULL CHECK (salary > 0)
);

-- ============================================================
-- DATA
-- ============================================================

INSERT INTO students (id, first_name, last_name, email, date_of_birth, enrolled_on) VALUES
    ( 1, 'Ada',      'Lovelace',  'ada.lovelace@example.edu',  '2003-12-10', '2024-09-01'),
    ( 2, 'Alan',     'Turing',    'alan.turing@example.edu',   '2004-06-23', '2024-09-01'),
    ( 3, 'Grace',    'Hopper',    'grace.hopper@example.edu',  '2003-12-09', '2024-09-01'),
    ( 4, 'Edsger',   'Dijkstra',  'edsger.d@example.edu',      '2004-05-11', '2024-09-15'),
    ( 5, 'Barbara',  'Liskov',    'barbara.liskov@example.edu','2003-11-07', '2024-09-15'),
    ( 6, 'Donald',   'Knuth',     'donald.knuth@example.edu',  '2004-01-10', '2025-01-12'),
    ( 7, 'Margaret', 'Hamilton',  'margaret.h@example.edu',    '2003-08-17', '2025-01-12'),
    ( 8, 'Ken',      'Thompson',  'ken.thompson@example.edu',  '2004-02-04', '2025-01-12'),
    ( 9, 'Leslie',   'Lamport',   'leslie.lamport@example.edu','2003-02-07', '2025-09-01'),
    (10, 'Frances',  'Allen',     'frances.allen@example.edu', '2004-08-04', '2025-09-01');

-- students 9 and 10 intentionally have no grades (useful for LEFT JOIN te
INSERT INTO grades (id, student_id, course, grade, graded_on) VALUES
    ( 1,  1, 'Mathematics',          95.50, '2025-01-20'),
    ( 2,  1, 'Physics',              88.00, '2025-01-22'),
    ( 3,  2, 'Cryptography',         99.00, '2025-01-20'),
    ( 4,  2, 'Mathematics',          91.25, '2025-01-21'),
    ( 5,  3, 'Compilers',            93.75, '2025-02-03'),
    ( 6,  4, 'Algorithms',           97.00, '2025-02-03'),
    ( 7,  5, 'Data Abstraction',     94.50, '2025-02-10'),
    ( 8,  6, 'Algorithms',           98.25, '2025-02-10'),
    ( 9,  7, 'Software Engineering', 96.00, '2025-02-14'),
    (10,  8, 'Operating Systems',    92.00, '2025-02-14');

-- grades 4 and 7 intentionally have no correspondance
INSERT INTO grades_correspondance (id, grade_id, author, message_type, message, sent_at) VALUES
    ( 1,  1, 'Prof. Babbage',  'feedback', 'Outstanding work on the analytical section.',        '2025-01-21 09:15:00+00'),
    ( 2,  1, 'Ada Lovelace',   'query',    'Could you clarify the deduction on question 4?',     '2025-01-21 14:02:00+00'),
    ( 3,  2, 'Prof. Newton',   'feedback', 'Solid grasp of mechanics; revise optics.',           '2025-01-23 11:30:00+00'),
    ( 4,  3, 'Prof. Shannon',  'notice',   'Top mark in the cohort this term.',                  '2025-01-20 16:45:00+00'),
    ( 5,  3, 'Alan Turing',    'query',    'Is the bonus cipher question included in this?',     '2025-01-22 08:05:00+00'),
    ( 6,  5, 'Prof. Backus',   'feedback', 'Parser implementation was clean and well tested.',   '2025-02-04 10:20:00+00'),
    ( 7,  6, 'Prof. Hoare',    'feedback', 'Elegant shortest-path proof. Minor notation issues.','2025-02-04 13:00:00+00'),
    ( 8,  8, 'Donald Knuth',   'appeal',   'Requesting review of the complexity analysis marks.','2025-02-11 09:40:00+00'),
    ( 9,  9, 'Prof. Brooks',   'feedback', 'Excellent requirements documentation.',              '2025-02-15 15:10:00+00'),
    (10, 10, 'Prof. Ritchie',  'notice',   'Lab attendance recorded as complete.',               '2025-02-15 17:25:00+00');

INSERT INTO staff (id, full_name, role, department, email, hired_on, salary) VALUES
    ( 1, 'Helena Marsh',   'Registrar',          'Administration', 'h.marsh@example.edu',    '2018-03-12',  62000.00),
    ( 2, 'Victor Osei',    'Lecturer',           'Mathematics',    'v.osei@example.edu',     '2016-09-01',  78500.00),
    ( 3, 'Priya Raman',    'Senior Lecturer',    'Computer Science','p.raman@example.edu',   '2014-01-20',  91000.00),
    ( 4, 'Tomas Lindqvist','Lab Technician',     'Physics',        't.lindqvist@example.edu','2021-06-14',  48000.00),
    ( 5, 'Aisha Bennani',  'Head of Department', 'Computer Science','a.bennani@example.edu', '2011-08-30', 118000.00),
    ( 6, 'Daniel Okafor',  'Librarian',          'Library',        'd.okafor@example.edu',   '2019-11-04',  54000.00),
    ( 7, 'Sofia Ricci',    'Student Counsellor', 'Student Support','s.ricci@example.edu',    '2020-02-17',  59500.00),
    ( 8, 'Martin Vogel',   'Lecturer',           'Engineering',    'm.vogel@example.edu',    '2017-04-03',  76000.00),
    ( 9, 'Chen Wei',       'Systems Administrator','IT Services',  'c.wei@example.edu',      '2015-07-22',  71000.00),
    (10, 'Nora Haddad',    'Finance Officer',    'Administration', 'n.haddad@example.edu',   '2022-09-05',  57000.00);

-- ------------------------------------------------------------
-- Explicit IDs don't advance an identity sequence — resync them
-- so future INSERTs without an id don't collide.
-- ------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('students',              'id'), (SELECT max(id) FROM students));
SELECT setval(pg_get_serial_sequence('grades',                'id'), (SELECT max(id) FROM grades));
SELECT setval(pg_get_serial_sequence('grades_correspondance', 'id'), (SELECT max(id) FROM grades_correspondance));
SELECT setval(pg_get_serial_sequence('staff',                 'id'), (SELECT max(id) FROM staff));

